#!/usr/bin/env bash

set -e

cd $(dirname $0)

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

# Build local docker images
./docker-build

# Tag local docker images
COMMIT_HASH=$(git rev-parse --short HEAD)
if [[ -n $(git status -s) ]]; then COMMIT_HASH=$COMMIT_HASH-dev; fi
if [ $(docker images -q filecanvas/app:$COMMIT_HASH) ]; then
	docker rmi filecanvas/app:$COMMIT_HASH
fi
if [ $(docker images -q filecanvas/router:$COMMIT_HASH) ]; then
	docker rmi filecanvas/router:$COMMIT_HASH
fi
docker tag filecanvas/app filecanvas/app:$COMMIT_HASH
docker tag filecanvas/router filecanvas/router:$COMMIT_HASH

if [ "$DOCKER_REGISTRY" ]; then
	if [ $(docker images -q $DOCKER_REGISTRY/filecanvas/app:$COMMIT_HASH) ]; then
		docker rmi $DOCKER_REGISTRY/filecanvas/app:$COMMIT_HASH
	fi
	if [ $(docker images -q $DOCKER_REGISTRY/filecanvas/router:$COMMIT_HASH) ]; then
		docker rmi $DOCKER_REGISTRY/filecanvas/router:$COMMIT_HASH
	fi
	docker tag filecanvas/app:$COMMIT_HASH $DOCKER_REGISTRY/filecanvas/app:$COMMIT_HASH
	docker tag filecanvas/router:$COMMIT_HASH $DOCKER_REGISTRY/filecanvas/router:$COMMIT_HASH
fi

# Prepare the deploy artifact
rm -rf .tmp/deploy
mkdir -p .tmp/deploy
rsync -a -v -L --delete --exclude '.*' .ebextensions/ .tmp/deploy/.ebextensions
if [ "$DOCKER_REGISTRY" ]; then
	REGISTRY_REPLACEMENT=$DOCKER_REGISTRY'\/'
else
	REGISTRY_REPLACEMENT=
fi
sed -e 's/filecanvas\/\([[:alpha:]]*\):latest/'$REGISTRY_REPLACEMENT'filecanvas\/\1:'$COMMIT_HASH'/' ./Dockerrun.aws.json > .tmp/deploy/Dockerrun.aws.json

# Build compiled assets
export NODE_ENV=production
THEMES_ROOT=.tmp/deploy/themes npm run postinstall

# Copy admin assets into artifact bundle
mkdir -p .tmp/deploy/templates/admin/assets
rsync -a -v -L --delete --exclude '.*' ./templates/admin/assets/ .tmp/deploy/templates/admin/assets

# Pack the deploy artifact
(cd .tmp/deploy; zip -FSr ../app.zip * .[^.]*)
