ssl:
  image: nginx
  links:
    - router
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./services/ssl/nginx.conf:/etc/nginx/nginx.conf
    - ${HTTPS_CERT}:/opt/ssl/cert.pem
    - ${HTTPS_KEY}:/opt/ssl/key.pem
router:
  image: filecanvas/router
  links:
    - redis
    - app
  ports:
    - "8080"
  environment:
    - HOST
    - REDIS_URL=redis://redis:6379
  volumes:
    - ${WWW_SITE_ROOT}:/var/www/subdomains/www
    - ${THEMES_ROOT}:/var/www/subdomains/themes
    - ${TEMPLATES_ROOT}/admin/assets:/var/www/subdomains/assets/admin
    - ${TEMPLATES_ROOT}/router:/var/www/templates
    - ${LOGS_ROOT}/nginx:/var/log/nginx
app:
  image: filecanvas/app
  links:
    - mongodb
    - redis
  ports:
    - "8081"
  environment:
    - HOST
    - HOST_PROTOCOL
    - HOST_PORT
    - NEW_RELIC_LICENSE_KEY
    - DROPBOX_APP_KEY
    - DROPBOX_APP_SECRET
    - DROPBOX_SITE_PATH
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_SITE_PATH
    - AWS_S3_BUCKET_THEME_UPLOADS
    - AWS_S3_BUCKET_DEMO_UPLOADS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - LOCAL
    - LOCAL_NAME
    - LOCAL_LABEL
    - LOCAL_SITE_PATH
    - LOCAL_BCRYPT_STRENGTH
    - COOKIE_SECRET
    - WWW_URL
    - ASSETS_URL
    - ADMIN_URL
    - THEMES_URL
    - SITE_USER_BCRYPT_STRENGTH
    - SESSION_DURATION
    - PORT=8081
    - TEMPLATES_ROOT=/var/templates
    - WWW_SITE_ROOT=/var/www
    - THEMES_ROOT=/var/themes
    - LOCAL_SITE_ROOT=/var/sites
    - MONGODB_URL=mongodb://mongodb/${DB_NAME}
    - REDIS_URL=redis://redis
  volumes:
    - ${TEMPLATES_ROOT}:/var/templates
    - ${WWW_SITE_ROOT}:/var/www
    - ${THEMES_ROOT}:/var/themes
    - ${LOCAL_SITE_ROOT}:/var/sites
    - ${LOGS_ROOT}/nodejs:/var/log/nodejs
mongodb:
  image: mongo
  volumes:
    - /data/db
redis:
  image: redis
