proxy:
  image: nginx
  links:
    - router
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./services/proxy/nginx.conf:/etc/nginx/nginx.conf
    - ${HTTPS_CERT}:/opt/ssl/cert.pem
    - ${HTTPS_KEY}:/opt/ssl/key.pem
    - ./data/logs/proxy:/var/log/nginx
router:
  build: ./services/nginx
  links:
    - app
  ports:
    - "8080"
  environment:
    - HOST
  volumes:
    - ./templates/www:/var/www/www
    - ./templates/admin/assets:/var/www/assets/admin
    - ./themes:/var/www/assets/themes
    - ./data/logs/nginx:/var/log/nginx
app:
  build: .
  links:
    - mongodb
    - redis
  ports:
    - "8081"
  environment:
    - HOST
    - HOST_PROTOCOL
    - HOST_PORT
    - NEW_RELIC_LICENSE_KEY
    - DROPBOX_APP_KEY
    - DROPBOX_APP_SECRET
    - DROPBOX_OAUTH2_LOGIN_CALLBACK
    - DROPBOX_OAUTH2_DEMO_LOGIN_CALLBACK
    - AWS_S3_BUCKET
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - GOOGLE
    - LOCAL
    - LOCAL_NAME
    - LOCAL_LABEL
    - LOCAL_SITE_PATH
    - LOCAL_BCRYPT_STRENGTH
    - COOKIE_SECRET
    - WWW_URL
    - ASSETS_URL
    - ADMIN_URL
    - THEMES_URL
    - SITE_USER_BCRYPT_STRENGTH
    - SESSION_DURATION
    - PORT=8081
    - LOCAL_SITE_ROOT=/var/sites
    - MONGODB_URL=mongodb://mongodb/${DB_NAME}
    - REDIS_URL=redis://redis
  volumes:
    - ${LOCAL_SITE_ROOT}:/var/sites
mongodb:
  image: mongo
  volumes:
    - /data/db
redis:
  image: redis
init:
  build: ./services/mongodb/worker
  links:
    - mongodb
  volumes:
    - ./services/mongodb/scripts/init.js:/opt/src/worker.js
  environment:
    - MONGODB_URL=mongodb://mongodb/${DB_NAME}
