#!/bin/sh
set -e

cd $(dirname $0)

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

export $(cat docker-compose.env | xargs)
trap "docker-compose stop && docker-compose rm -f" EXIT
docker-compose up
