#!/bin/bash
set -e

cd $(dirname $0)

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

# Get the current Git commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)
if [[ -n $(git status -s) ]]; then COMMIT_HASH=$COMMIT_HASH-dev; fi

# Tag local docker images
docker tag -f filecanvas/app:$COMMIT_HASH 296296715593.dkr.ecr.us-east-1.amazonaws.com/filecanvas/app:$COMMIT_HASH
docker tag -f filecanvas/router:$COMMIT_HASH 296296715593.dkr.ecr.us-east-1.amazonaws.com/filecanvas/router:$COMMIT_HASH

# Start background services
(docker run --rm -p 6379:6379 redis) &
(docker run --rm -p 27017:27017 mongo) &

# Run bundled app from deploy folder
mkdir -p .tmp/deploy/.elasticbeanstalk
cp -f .elasticbeanstalk/config.yml .tmp/deploy/.elasticbeanstalk/config.yml
cp -f .elasticbeanstalk/.localstate .tmp/deploy/.elasticbeanstalk/.localstate
(cd .tmp/deploy; eb local run) &


# Start SSL proxy
sleep 5;
docker run --rm\
	-p 443:443\
	--link elasticbeanstalk_router_1:router\
	-v $(pwd)/services/ssl/nginx.conf:/etc/nginx/nginx.conf\
	-v $(pwd)/services/ssl/certs/filecanvas-vm.com/cert.pem:/opt/ssl/cert.pem\
	-v $(pwd)/services/ssl/certs/filecanvas-vm.com/key.pem:/opt/ssl/key.pem\
	nginx
