#!/bin/bash
set -e

trap "killall mongod" EXIT

cd $(dirname $0)

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

# Get the current Git commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)

# Tag local docker images
docker tag -f filecanvas/app:$COMMIT_HASH 296296715593.dkr.ecr.us-east-1.amazonaws.com/filecanvas/app:$COMMIT_HASH
docker tag -f filecanvas/router:$COMMIT_HASH 296296715593.dkr.ecr.us-east-1.amazonaws.com/filecanvas/router:$COMMIT_HASH

# Start background services
(mongod --dbpath data/mongodb/db) &
(redis-server /usr/local/etc/redis.conf) &

# Run bundled app from deploy folder
mkdir -p .tmp/deploy/.elasticbeanstalk
cp -f .elasticbeanstalk/config.yml .tmp/deploy/.elasticbeanstalk/config.yml
cp -f .elasticbeanstalk/.localstate .tmp/deploy/.elasticbeanstalk/.localstate
(cd .tmp/deploy; eb local run) &

# Start SSL proxy
sleep 5;
docker run\
	-p 443:443\
	--link elasticbeanstalk_router_1:router\
	-v $(pwd)/services/ssl/nginx.conf:/etc/nginx/nginx.conf\
	-v $(pwd)/services/ssl/certs/filecanvas.docker/cert.pem:/opt/ssl/cert.pem\
	-v $(pwd)/services/ssl/certs/filecanvas.docker/key.pem:/opt/ssl/key.pem\
	--name filecanvas_ssl\
	nginx
