#!/bin/bash
set -e

trap "killall mongod" EXIT

cd $(dirname $0)

(mongod --dbpath data/mongodb/db) &
(redis-server /usr/local/etc/redis.conf) &

export NODE_ENV=development

npm run postinstall

export $(cat .env | sed -e 's/#.*$//' | xargs)

npm run prestart

foreman start -f Procfile.dev
