#!/usr/bin/env node
'use strict';

var fs = require('fs');
var path = require('path');
var mkdirp = require('mkdirp');

var build = require('./src/build');

var args = process.argv.slice(['node', 'script.js'].length);
try {
	if (args.length !== 2) { throw new Error('Usage: build <inputDir> <outputDir>'); }
	if (args[0] === args[1]) { throw new Error('Invalid output path'); }
	if (!process.env.HOST) { throw new Error('Missing HOST environment variable'); }
} catch(error) {
	exit(error);
}

var source = fs.realpathSync(args[0]);
var destination = path.resolve(args[1]);
var context = {
	host: {
		hostname: process.env.HOST || null,
		protocol: process.env.HOST_PROTOCOL || 'https:',
		port: Number(process.env.HOST_PORT || ((process.env.HOST_PROTOCOL || 'https:') === 'https:' ? 443 : 80))
	},
	analytics: {
		google: process.env.GOOGLE_ANALYTICS_ID_WWW,
		segment: process.env.SEGMENT_ANALYTICS_ID_WWW
	}
};

process.stdout.write('Generating static site...\n');
ensureDirectoryExists(destination)
	.then(function() {
		process.stdout.write('Copying files from ' + source + '\n');
		return build(source, destination, context)
			.on('copyFileStart', function(copyOperation) {
				process.stdout.write('Copying ' + copyOperation.src + '\n');
			});
	})
	.then(function(results) {
		process.stdout.write(results.length + ' ' + (results.length === 1 ? 'file' : 'files') + ' copied\n');
	})
	.catch(function(error) {
		exit(error);
	});


function exit(error) {
	if (error) {
		process.stderr.write('\u001b[31m' + 'Error: ' + error.message + '\u001b[39m' + '\n');
		process.exit(1);
	} else {
		process.exit();
	}
}

function ensureDirectoryExists(path) {
	return new Promise(function(resolve, reject) {
		mkdirp(path, function(error) {
			if (error) {
				reject(error);
			} else {
				resolve(error);
			}
		});
	});
}
