#!/usr/bin/env bash
set -e

cd $(dirname $0)

INPUT_DIR=$PWD/src
OUTPUT_DIR=$PWD/dist

HOST_PROTOCOL=${HOST_PROTOCOL:-$([ "$HTTPS" == "true" ] && echo "https:" || echo "http:")}
HOST_PORT=${HOST_PORT:-$([ "$HOST_PROTOCOL" == "https:" ] && echo "$HTTPS_PORT" || echo "$PORT")}

# Build www site
echo "Generating www site..."
rm -rf $OUTPUT_DIR
HOST=$HOST \
HOST_PROTOCOL=$HOST_PROTOCOL \
HOST_PORT=$HOST_PORT \
	./scripts/build $INPUT_DIR $OUTPUT_DIR
