FROM tianon/true

VOLUME /var/templates

COPY router/data /var/templates/router/
COPY app/data /var/templates/app/
COPY site/data /var/templates/site/
COPY www/data /var/templates/www/
COPY themes/data /var/templates/themes/
