FROM tianon/true

VOLUME /var/templates

COPY router/dist /var/templates/router/
COPY app/dist /var/templates/app/
COPY assets/dist /var/templates/assets/
COPY site/dist /var/templates/site/
COPY themes/dist /var/templates/themes/
COPY www/src /var/templates/www/
