#!/usr/bin/env bash
set -e

if [[ -n $(git status -s) ]]; then
	echo "ERROR: There are uncommitted changes"
	exit 1
fi

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

# Get the current Git commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)

# Upload local docker images
IMAGES=(
	"filecanvas/app"
	"filecanvas/router"
	"filecanvas/templates"
)
DOCKER_REGISTRY=296296715593.dkr.ecr.us-east-1.amazonaws.com
for image in "${IMAGES[@]}"; do
	docker push $DOCKER_REGISTRY/$image:$COMMIT_HASH
done

# Deploy to Elastic Beanstalk
eb deploy
