#!/usr/bin/env bash
set -e

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

export $(cat docker-compose.env | sed -e 's/#.*$//' | xargs)

export NODE_ENV=production
trap "docker-compose stop && docker-compose rm -f" EXIT
docker-compose up
