#!/usr/bin/env bash
set -e

if [[ -n $(git status -s) ]]; then
	echo "ERROR: There are uncommitted changes"
	exit 1
fi

if [ $(docker-machine status default) != "Running" ]; then
	docker-machine start default
fi

eval $(docker-machine env default)

# Get the current Git commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)

# Bundle application
DOCKER_REGISTRY=296296715593.dkr.ecr.us-east-1.amazonaws.com
DOCKER_REGISTRY=$DOCKER_REGISTRY \
	npm run docker-bundle

# Upload local docker images
docker push $DOCKER_REGISTRY/filecanvas/app:$COMMIT_HASH
docker push $DOCKER_REGISTRY/filecanvas/router:$COMMIT_HASH

# Deploy to Elastic Beanstalk
eb deploy
