#!/usr/bin/env bash
set -e

ROOT_DIR="$PWD"
DATA_DIR="$ROOT_DIR/.tmp/data"
export NODE_ENV=development
export $(cat .env | sed -e 's/#.*$//' | xargs)

echo "Building templates..."
NODE_ENV=development \
	./templates/build

echo "Linking template directories..."
rm -rf $DATA_DIR/templates
mkdir -p $DATA_DIR/templates
ln -s $ROOT_DIR/templates/app/dist/ $DATA_DIR/templates/app
ln -s $ROOT_DIR/templates/assets/dist/ $DATA_DIR/templates/assets
ln -s $ROOT_DIR/templates/router/dist/ $DATA_DIR/templates/router
ln -s $ROOT_DIR/templates/site/dist/ $DATA_DIR/templates/site
ln -s $ROOT_DIR/templates/themes/dist/ $DATA_DIR/templates/themes
ln -s $ROOT_DIR/templates/www/dist/ $DATA_DIR/templates/www

echo "Writing nginx configuration..."
rm -rf $DATA_DIR/nginx
mkdir -p $DATA_DIR/nginx
cp services/router/init.sh $DATA_DIR/nginx/init.sh
cp -r services/router/nginx/conf/ $DATA_DIR/nginx/config/
NGINX_CONFIG_REPLACEMENTS=(
	's/\/opt\/openresty\/nginx\/conf\//'${DATA_DIR//\//\\\/}'\/nginx\/config\//g'
	's/\/opt\/openresty\/lua-resty-template\//'${PWD//\//\\\/}'\/services\/router\/plugins\/lua-resty-template\/lib\//g'
	's/\/var\/templates\//'${DATA_DIR//\//\\\/}'\/templates\//g'
	's/\/var\/run\/nginx.pid/'${DATA_DIR//\//\\\/}'\/nginx\/run\/nginx.pid/g'
	's/\/var\/log\/nginx\//'${DATA_DIR//\//\\\/}'\/logs\/nginx\//g'
	's/sed -i/sed -i '"''"'/g'
)
for replacement in "${NGINX_CONFIG_REPLACEMENTS[@]}"; do
	sed -i '' "$replacement" $DATA_DIR/nginx/init.sh $DATA_DIR/nginx/config/nginx.conf $DATA_DIR/nginx/config/error.conf $DATA_DIR/nginx/config/template.d/*
done
mkdir -p $DATA_DIR/nginx/run
mkdir -p $DATA_DIR/logs/nginx
$DATA_DIR/nginx/init.sh

echo "Writing SSL configuration..."
rm -rf $DATA_DIR/ssl
mkdir -p $DATA_DIR/ssl
mkdir -p $DATA_DIR/ssl/config
cp services/ssl/nginx.conf $DATA_DIR/ssl/config/nginx.conf
NGINX_CONFIG_REPLACEMENTS=(
	's/\/opt\/ssl\//'${DATA_DIR//\//\\\/}'\/ssl\/certs\//g'
	's/listen 80;/listen 8000;/g'
	's/listen 443 ssl;/listen 4443 ssl;/g'
	's/X-Forwarded-Port 443;/X-Forwarded-Port 4443;/g'
)
for replacement in "${NGINX_CONFIG_REPLACEMENTS[@]}"; do
	sed -i '' "$replacement" $DATA_DIR/ssl/config/nginx.conf
done
ln -s $ROOT_DIR/services/ssl/certs/dev-filecanvas.com $DATA_DIR/ssl/certs

echo "Starting services..."
(cd services/storage && npm start) &
(nginx -c $DATA_DIR/ssl/config/nginx.conf -g 'daemon off;') &
(openresty -c $DATA_DIR/nginx/config/nginx.conf -g 'daemon off;') &
mkdir -p $DATA_DIR/mongodb/db
trap "killall mongod" EXIT
(mongod --dbpath $DATA_DIR/mongodb/db) &
(redis-server /usr/local/etc/redis.conf) &

echo "Launching app..."
foreman start -f Procfile.dev
