#!/usr/bin/env bash
set -e

# Build www site
echo "Generating www site..."
HOST_PROTOCOL=${HOST_PROTOCOL:-$([ "$HTTPS" == "true" ] && echo "https:" || echo "http:")}
HOST_PORT=${HOST_PORT:-$([ "$HOST_PROTOCOL" == "https:" ] && echo "$HTTPS_PORT" || echo "$PORT")}

HOST=$HOST \
HOST_PROTOCOL=$HOST_PROTOCOL \
HOST_PORT=$HOST_PORT \
TEMPLATE_DIR=$TEMPLATES_WWW \
OUTPUT_DIR=$WWW_SITE_ROOT \
	./scripts/www/build
