#!/usr/bin/env bash
set -e

cd $(dirname $0)

TEMPLATES_DIR=$PWD/src/templates
EXAMPLES_DIR=$PWD/src/examples
OUTPUT_DIR=$PWD/dist

rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

echo "Building themes..."
mkdir -p $OUTPUT_DIR/themes
for theme in $(ls $TEMPLATES_DIR/themes); do
	./scripts/bundle $TEMPLATES_DIR/themes/$theme $OUTPUT_DIR/themes/$theme
done

echo "Building examples..."
mkdir -p $OUTPUT_DIR/examples
for example in $(ls $EXAMPLES_DIR); do
	./scripts/render $EXAMPLES_DIR/$example $OUTPUT_DIR/examples/$example
done
