#!/usr/bin/env bash
set -e

cd $(dirname $0)

INPUT_DIR=$PWD/templates
OUTPUT_DIR=$PWD/data

rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

echo "Building client libraries..."
if [ "$NODE_ENV" == 'production' ]; then
	rm -f $INPUT_DIR/_common/js/filecanvas-theme.js
	rm -f $INPUT_DIR/_common/js/filecanvas-theme.js.map
	(cd client; webpack -p $INPUT_DIR/_common/js/filecanvas-theme.js)
else
	(cd client; webpack -d $INPUT_DIR/_common/js/filecanvas-theme.js)
fi

if [ "$NODE_ENV" != 'production' ]; then
	echo "Copying common theme code..."
	cp -r $INPUT_DIR/_common $OUTPUT_DIR/_common/
fi

echo "Building themes..."
mkdir -p $OUTPUT_DIR/themes
for theme in $(ls $INPUT_DIR/themes); do
	./scripts/bundle $INPUT_DIR/themes/$theme $OUTPUT_DIR/themes/$theme
done
